ALTER TABLE users ADD COLUMN home_currency VARCHAR(3);
ALTER TABLE transactions ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT 'USD';
ALTER TABLE pay_schedules ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT 'USD';
